### ISSUE TITLE
idk what to do with this. this is half of the map scrolling code

### ISSUE THREAD

**Issue by Spaghettimonstar** [danyooo/final30passionproj#19]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BackgroundScroll : MonoBehaviour
{
    private Transform cameraTransform;
    private Vector3 lastCameraPosition;

    private void Start()
    {
        cameraTransform = Camera.main.transform;
        lastCameraPosition = cameraTransform.position;
    }

    private void LateUpdate() {}
    {
       Vector3 deltaMovement = cameraTransform.position - lastCameraPosition;
    float parallaxEffectMultiplier = .55;
    transform.position += deltaMovement* parallaxEffectMultiplier;
        lastCameraPosition = cameraTransform.position;
    }
}

**Comment by danyooo** [comment]
If you attach the background to the camera it should stay
that is, once the camera follows the character

**Comment by danyooo** [comment]
Do this by making it a "child" of the camera, dragging the picture into the camera

**Comment by Spaghettimonstar** [comment]
public class Camera : MonoBehaviour
{
public GameObject target;
//start is called before the first frame update
void Start()
{

}

//Update is called once per frame
void Update()
{
transform.position = new Vector3(target.transform.position.x, transform.position.y, - 10);
}

}

**Comment by Spaghettimonstar** [comment]
> public class Camera : MonoBehaviour { public GameObject target; //start is called before the first frame update void Start() {
> 
> }
> 
> //Update is called once per frame void Update() { transform.position = new Vector3(target.transform.position.x, transform.position.y, - 10); }
> 
> }

CAMERA MOVEMENT
